FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Make port 4200 available to the world outside this container
EXPOSE 4200

# Define the command to run your app using CMD which defines your runtime
CMD ["npm", "run", "start"]
