# Base image
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Your app binds to port 3000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 5173
EXPOSE 24678

# Define the command to run your app using CMD which defines your runtime
# Starts the development server with live reloading
CMD [ "npm", "run", "dev" ]
