# Use the node:18-alpine image for a smaller footprint
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or alternatively yarn.lock)
COPY package*.json ./

# Ensure that NODE_ENV is set to 'development' to install devDependencies
ENV NODE_ENV=development

# Install all dependencies, including devDependencies
RUN npm install --also=dev

# uninstall the current bcrypt modules
RUN npm uninstall bcrypt

# install the bcrypt modules for the machine
RUN npm install bcrypt

# Copy the rest of your application code to the container
COPY . .

# Expose the application port and the debugger port
EXPOSE 3001 9229

# Command to run your application in development mode
CMD ["npm", "run", "start:dev"]
